
maci_admin_view:
    path:  /view/{section}/{entity}/{action}/{id}/{relation}/{relAction}/{bridge}
    defaults: { _controller: MaciAdminBundle:View:view, section: false, entity: false, action: false, id: false, relation: false, relAction: false, bridge: false }

maci_admin_dashboard:
    path:  /view/{section}
    defaults: { _controller: MaciAdminBundle:View:view }

maci_admin_ajax:
    path:  /ajax
    defaults: { _controller: MaciAdminBundle:View:ajax }

maci_admin_not_found:
    path:  /not-found
    defaults: { _controller: MaciAdminBundle:View:notFound }

maci_admin:
    path:  /
    defaults: { _controller: MaciAdminBundle:View:index }
